name = "chicken-road-appbonus-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chicken-road-appbonus.com"
HMAC_KEY = "1996f4a389c57e3ed3b8aa6e60b12b5485798a2707475b8690e5843359740362"
COOKIE_NAME = "2e1"
PLAY_PATH = "play-now"
BUTTON_ID = "pbec2ef0b69a866705c2693e0461c59e5"
GATE_SALT = "972edad030f8821b"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "l45q"
CTA_SELECTOR = ".play-button"
